Update SFR Direction
biometricITC/cPP-biometrics pull request #333
Opened 2021-06-08 08:39 UTC by n-kai

Complete "6.2. PP_MD_V3.3 Security Functional Requirements Direction" except adding EA for modified SFR to BIOSD

2021-06-08 18:04 UTC, woodbe commented
My update also included a few changes for the extended component definitions where we had made updates to the main SFR but not the matching ECD change, so they are included here.

I did not make any changes to the BIOSD as I didn't see any actual change from what had been added for the FPT_KST_EXT requirements as we aren't making any further dependencies on the MDF that we need to do.

2021-06-09 20:00 UTC, woodbe requested changes

2021-06-11 05:16 UTC, n-kai commented on Protection Profile/BiocPP.adoc
> +===== Class: Cryptographic Support (FCS)
I agree with the first to remove text for key hierarchy.

I added "all keys created upon successful biometric enrolment and verification must be generated, derived, combined, released and destroyed according to SFRs in this class" to address the following NIAP comment. 

Section 8.3.3 ,FPT_BDP_EXT.3.1: This comment is more on the SD activity. This activity talks about encryption, and in terms of NIAP PP-Modules and PPs we require any cryptographic requirements to be specified. The SD currently indicates that the vendor gives a list of cryptographic mechanisms used--this is not acceptable. **This PP should** either specify what is required (ideally through either optional requirements or selection-based requirements) and/or **point to requirements in the Base PP**.

Biometric system (TOE for PPM) needs to generate a KEK, unlock this KEK upon the successful biometric verification and decrypt DEK to unlock the device. So key generation for KEK shall meet FCS_CKM_EXT.3 in MDFPP and key decryption shall meet FCS_COP.1 (or add additional SFRs to MDFPP if the key generation or decryption use different algorithm that are not defined in MDFPP) and .vendor needs to point crypto functions the biometirc system uses to crypt requirement in MDFPP like FCS_CKM_EXT.3 in BMD or KMD.

2021-06-11 05:18 UTC, n-kai commented on Protection Profile/BiocPP.adoc
> +*FPT_KST_EXT.2.1*:: The TSF shall not transmit any plaintext key material *and biometric data* outside the security boundary of the TOE.
I agree and I will update it later.

2021-06-11 05:26 UTC, n-kai commented on Protection Profile/BiocPP.adoc
> +*FPT_KST_EXT.2.1*:: The TSF shall not transmit any plaintext key material *and biometric data* outside the security boundary of the TOE.
I am looking at wrong branch. You have done this by another PR

2021-06-11 05:29 UTC, n-kai commented on Protection Profile/BiocPP.adoc
> +This PP-Module does not modify SFRs in FIA class as it is defined in the <<PP_MD_V3.3>>. However, if the TOE claims conformance to a PP-Configuration that includes this PP-Module, only eye, face, fin
OK I agree

2021-06-11 11:35 UTC, woodbe commented on Protection Profile/BiocPP.adoc
> +===== Class: Cryptographic Support (FCS)
Yeah, I came around to this, so it is good.

2021-06-11 11:46 UTC, woodbe commented on Protection Profile/BiocPP.adoc
> +This PP-Module does not modify SFRs in FIA class as it is defined in the <<PP_MD_V3.3>>. However, if the TOE claims conformance to a PP-Configuration that includes this PP-Module, only eye, face, fin
new commit with this removed

2021-06-11 11:46 UTC, woodbe commented on Protection Profile/BiocPP.adoc
> +*FPT_KST_EXT.2.1*:: The TSF shall not transmit any plaintext key material *and biometric data* outside the security boundary of the TOE.
edited here as well (to make sure it doesn't get mixed up later).

2021-06-11 11:46 UTC, woodbe approved these changes

2021-06-11 11:47 UTC, merged