IAPAR update
biometricITC/cPP-biometrics pull request #347
Opened 2021-06-16 14:53 UTC by woodbe

This is to close #343

One concern I have here is that I updated FIA_MBE_EXT.3.1 to match, but technically IAPAR is for verification, so I'm not sure we can use that for enrolment. I don't know what to do if we don't, since then the enrolment requirement is vague, but I also don't know if an IAPAR for verification is in any way equivalent for enrolment.

I didn't make any further changes in terms of tables or such that would explain the calculations or anything differently (or more explicitly), so we may end up needing to do something along those lines, but I'm not sure.

2021-06-17 11:05 UTC, gfiumara commented
For enrolment, you maybe want "bona fide presentation classification error rate (BPCER): _proportion of bona fide presentations incorrectly classified as presentation attacks in a specific scenario_," and/or the inverse, "attack presentation classification error rate (APCER): _proportion of attack presentations using the same PAI species incorrectly classified as bona fide presentations in a specific scenario_."

2021-06-26 03:05 UTC, n-kai requested changes
I checked the latest ISO 30107-3 that is under revision. you can't use IAPAR for enrollment so new term something like below should be defined and this new term should be used in FIA_MBV_EXT.3.1

**Imposter Attack Presentation Accept Rate for enrollment (IAPARE)
In a full-system evaluation of a enrollment system, proportion of impostor presentation attacks using the same artefact type that result in a successful enrollement**

2021-06-28 16:17 UTC, gfiumara commented
I don't think I agree with creating a new term IAPARE that is not defined by ISO. Enrolment doesn't deal with a verification system at all, it would only deal with the "data capture subsystem," which is the term specified in the published ISO/IEC 30107-3:2017. The second A in IAPAR is about acceptance, formally M for match, but ISO/IEC depreciated using _match_ this way. This wouldn't follow for enrolment.

If anything, the term should be IAPE(nrollment)Rate, but I think that might as well be the _attack presentation acquisition rate (APAR)_ ("proportion of attack presentations using the same PAI species from which the data capture subsystem acquires a biometric sample of sufficient quality").

2021-06-28 16:48 UTC, woodbe commented
Another option would be to not specify anything for IAPAR for enrolment and go back to what it was before.

I will admit I read the comment wrong and thought this was in the draft ISO (when I was reading the comment), so having it there is to capture it. I am not certain how to handle the enrolment case, as it is definitely the most tricky since you don't have anything to compare with readily at that point.

2021-06-29 06:20 UTC, n-kai commented
I agree with "Another option would be to not specify anything for IAPAR for enrolment and go back to what it was before.". PAD for enrolment is optional requirement and ISO/IEC 30107-3 doesn't require to report the error rate like IAPAR.

2021-06-29 12:10 UTC, woodbe commented
I have removed the FIA_MBE_EXT.3 requirement changes to leave it as it was originally at this point. So the changes are now just the IAPAR on the FIA_MBV_EXT.3 requirement

2021-06-29 13:38 UTC, n-kai approved these changes

2021-06-29 13:56 UTC, gfiumara approved these changes

2021-06-29 14:20 UTC, woodbe commented
call this out for comment in the public review

2021-06-29 14:20 UTC, woodbe commented
agreed to be merged on the call

2021-06-29 15:20 UTC, merged