date and allowed list
biometricITC/cPP-biometrics pull request #392
Opened 2022-08-18 15:27 UTC by woodbe

To match up with the PP_MDF release the following changes were made:

- release dates for the docs all changed to match with the dates of the PP_MDF date (September 12, 2022)
- The specific PP-Modules that are allowed was removed and replaced by a link to a new page on the website. This will prevent needing to revise the PPM every time NIAP publishes as new Module update as the website page can be done easily.
- in the PP-Config (which will not be used as NIAP will create their own), I changed the reference to the PPM to MOD_BIO_V1.0 which matches the NIAP format for the names

2022-08-22 08:47 UTC, n-kai requested changes
Please merge #393 into Date & allowed list update branch.

2022-08-23 01:07 UTC, n-kai approved these changes

2022-08-23 12:37 UTC, ccparran approved these changes

2022-08-23 13:16 UTC, gregott approved these changes

2022-08-23 13:33 UTC, gregott approved these changes

2022-08-23 14:10 UTC, merged